FROM python:3.6.7

ENV FLASK_APP main.py

WORKDIR /home/lucas/Escritorio/Facultad/Cuartoaño/NSQL/tp4 CryptoApp/Cryptongo-master/agent

RUN pip3 install requests flask pymongo

COPY  main.py  ./api.py

EXPOSE 5000

CMD ["flask", "run"]